// <auto-generated />
using System;
using DiplomaWork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomaWork.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiplomaWork.Data.Models.Classroom", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            ID = "classroom-id-1",
                            Name = "Classroom 1"
                        },
                        new
                        {
                            ID = "classroom-id-2",
                            Name = "Classroom 2"
                        },
                        new
                        {
                            ID = "classroom-id-3",
                            Name = "Classroom 3"
                        },
                        new
                        {
                            ID = "classroom-id-4",
                            Name = "Classroom 4"
                        });
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Group", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TeacherID")
                        .IsUnique()
                        .HasFilter("[TeacherID] IS NOT NULL");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            ID = "group-id-1",
                            Name = "Group A",
                            TeacherID = "teacher-id-1"
                        },
                        new
                        {
                            ID = "group-id-2",
                            Name = "Group B",
                            TeacherID = "teacher-id-2"
                        },
                        new
                        {
                            ID = "group-id-3",
                            Name = "Group C",
                            TeacherID = "teacher-id-3"
                        },
                        new
                        {
                            ID = "group-id-4",
                            Name = "Group D",
                            TeacherID = "teacher-id-4"
                        });
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Lesson", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassroomID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ClassroomID")
                        .IsUnique()
                        .HasFilter("[ClassroomID] IS NOT NULL");

                    b.HasIndex("GroupID")
                        .IsUnique()
                        .HasFilter("[GroupID] IS NOT NULL");

                    b.HasIndex("SubjectID")
                        .IsUnique()
                        .HasFilter("[SubjectID] IS NOT NULL");

                    b.HasIndex("TeacherID")
                        .IsUnique()
                        .HasFilter("[TeacherID] IS NOT NULL");

                    b.HasIndex("DayOfWeek", "Number", "GroupID")
                        .IsUnique()
                        .HasFilter("[GroupID] IS NOT NULL");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            ID = "91900b29-3e80-442b-a1e8-5cd7ed7d3075",
                            ClassroomID = "classroom-id-1",
                            DayOfWeek = 1,
                            GroupID = "group-id-1",
                            Number = 1,
                            SubjectID = "subject-id-1",
                            TeacherID = "teacher-id-1"
                        },
                        new
                        {
                            ID = "dc8efc70-88f6-4e32-877a-eefc9b29ab75",
                            ClassroomID = "classroom-id-2",
                            DayOfWeek = 1,
                            GroupID = "group-id-2",
                            Number = 2,
                            SubjectID = "subject-id-2",
                            TeacherID = "teacher-id-2"
                        },
                        new
                        {
                            ID = "5446f3e2-b5d2-4bb9-92e4-387be513fc11",
                            ClassroomID = "classroom-id-3",
                            DayOfWeek = 1,
                            GroupID = "group-id-3",
                            Number = 3,
                            SubjectID = "subject-id-3",
                            TeacherID = "teacher-id-3"
                        },
                        new
                        {
                            ID = "c1974418-9627-4872-afce-4b6913cd1a92",
                            ClassroomID = "classroom-id-4",
                            DayOfWeek = 1,
                            GroupID = "group-id-4",
                            Number = 4,
                            SubjectID = "subject-id-4",
                            TeacherID = "teacher-id-4"
                        },
                        new
                        {
                            ID = "d0003c37-5c70-416e-9ab7-dfd317ba8200",
                            ClassroomID = "classroom-id-2",
                            DayOfWeek = 2,
                            GroupID = "group-id-2",
                            Number = 1,
                            SubjectID = "subject-id-2",
                            TeacherID = "teacher-id-2"
                        },
                        new
                        {
                            ID = "de172efd-ac47-430d-930a-5e85a9c9586b",
                            ClassroomID = "classroom-id-3",
                            DayOfWeek = 2,
                            GroupID = "group-id-3",
                            Number = 2,
                            SubjectID = "subject-id-3",
                            TeacherID = "teacher-id-3"
                        },
                        new
                        {
                            ID = "41cc933f-1e16-49b3-8c85-9521cc89ea2a",
                            ClassroomID = "classroom-id-4",
                            DayOfWeek = 2,
                            GroupID = "group-id-4",
                            Number = 3,
                            SubjectID = "subject-id-4",
                            TeacherID = "teacher-id-4"
                        },
                        new
                        {
                            ID = "e67389da-9203-4153-98d9-a5a7b04756b0",
                            ClassroomID = "classroom-id-1",
                            DayOfWeek = 2,
                            GroupID = "group-id-1",
                            Number = 4,
                            SubjectID = "subject-id-1",
                            TeacherID = "teacher-id-1"
                        },
                        new
                        {
                            ID = "b0e64d12-96f4-4f27-95b7-d518c2ec6b11",
                            ClassroomID = "classroom-id-3",
                            DayOfWeek = 3,
                            GroupID = "group-id-3",
                            Number = 1,
                            SubjectID = "subject-id-3",
                            TeacherID = "teacher-id-3"
                        },
                        new
                        {
                            ID = "04376084-ed86-4e77-966f-c1d15d0c88b5",
                            ClassroomID = "classroom-id-4",
                            DayOfWeek = 3,
                            GroupID = "group-id-4",
                            Number = 2,
                            SubjectID = "subject-id-4",
                            TeacherID = "teacher-id-4"
                        },
                        new
                        {
                            ID = "efc6ed93-82f3-4ceb-a2eb-b0b51f7797d1",
                            ClassroomID = "classroom-id-1",
                            DayOfWeek = 3,
                            GroupID = "group-id-1",
                            Number = 3,
                            SubjectID = "subject-id-1",
                            TeacherID = "teacher-id-1"
                        },
                        new
                        {
                            ID = "b6a00531-4cf6-4f87-a47a-5b1b44454e51",
                            ClassroomID = "classroom-id-2",
                            DayOfWeek = 3,
                            GroupID = "group-id-2",
                            Number = 4,
                            SubjectID = "subject-id-2",
                            TeacherID = "teacher-id-2"
                        },
                        new
                        {
                            ID = "988c70c9-ddd0-4c9f-af3c-7635ed1f7654",
                            ClassroomID = "classroom-id-4",
                            DayOfWeek = 4,
                            GroupID = "group-id-4",
                            Number = 1,
                            SubjectID = "subject-id-4",
                            TeacherID = "teacher-id-4"
                        },
                        new
                        {
                            ID = "48209c1b-e8ee-42cd-9659-44fa5bc41989",
                            ClassroomID = "classroom-id-1",
                            DayOfWeek = 4,
                            GroupID = "group-id-1",
                            Number = 2,
                            SubjectID = "subject-id-1",
                            TeacherID = "teacher-id-1"
                        },
                        new
                        {
                            ID = "257bf0db-6194-4d57-8d68-52ec85563cfa",
                            ClassroomID = "classroom-id-2",
                            DayOfWeek = 4,
                            GroupID = "group-id-2",
                            Number = 3,
                            SubjectID = "subject-id-2",
                            TeacherID = "teacher-id-2"
                        },
                        new
                        {
                            ID = "0745cfc5-b83b-46ec-b48a-632cded3fc3c",
                            ClassroomID = "classroom-id-3",
                            DayOfWeek = 4,
                            GroupID = "group-id-3",
                            Number = 4,
                            SubjectID = "subject-id-3",
                            TeacherID = "teacher-id-3"
                        },
                        new
                        {
                            ID = "ad2f61bb-9690-4752-989a-298be21a6f13",
                            ClassroomID = "classroom-id-1",
                            DayOfWeek = 5,
                            GroupID = "group-id-1",
                            Number = 1,
                            SubjectID = "subject-id-1",
                            TeacherID = "teacher-id-1"
                        },
                        new
                        {
                            ID = "6ad4428d-62f1-4c34-8aee-f89f6fbf02f2",
                            ClassroomID = "classroom-id-2",
                            DayOfWeek = 5,
                            GroupID = "group-id-2",
                            Number = 2,
                            SubjectID = "subject-id-2",
                            TeacherID = "teacher-id-2"
                        },
                        new
                        {
                            ID = "9e983c28-04a1-45e2-99a6-9ffc217b9336",
                            ClassroomID = "classroom-id-3",
                            DayOfWeek = 5,
                            GroupID = "group-id-3",
                            Number = 3,
                            SubjectID = "subject-id-3",
                            TeacherID = "teacher-id-3"
                        },
                        new
                        {
                            ID = "acb322b7-0aee-41d8-816a-32f6bf05abe0",
                            ClassroomID = "classroom-id-4",
                            DayOfWeek = 5,
                            GroupID = "group-id-4",
                            Number = 4,
                            SubjectID = "subject-id-4",
                            TeacherID = "teacher-id-4"
                        });
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Subject", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            ID = "subject-id-1",
                            Name = "Math"
                        },
                        new
                        {
                            ID = "subject-id-2",
                            Name = "Science"
                        },
                        new
                        {
                            ID = "subject-id-3",
                            Name = "English"
                        },
                        new
                        {
                            ID = "subject-id-4",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique()
                        .HasFilter("[LastName] IS NOT NULL");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = "teacher-id-1",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = "teacher-id-2",
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = "teacher-id-3",
                            FirstName = "David",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = "teacher-id-4",
                            FirstName = "Emily",
                            LastName = "Wilson"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Group", b =>
                {
                    b.HasOne("DiplomaWork.Data.Models.Teacher", "Teacher")
                        .WithOne("Group")
                        .HasForeignKey("DiplomaWork.Data.Models.Group", "TeacherID");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Lesson", b =>
                {
                    b.HasOne("DiplomaWork.Data.Models.Classroom", "Classroom")
                        .WithOne("Lesson")
                        .HasForeignKey("DiplomaWork.Data.Models.Lesson", "ClassroomID");

                    b.HasOne("DiplomaWork.Data.Models.Group", "Group")
                        .WithOne("Lesson")
                        .HasForeignKey("DiplomaWork.Data.Models.Lesson", "GroupID");

                    b.HasOne("DiplomaWork.Data.Models.Subject", "Subject")
                        .WithOne("Lesson")
                        .HasForeignKey("DiplomaWork.Data.Models.Lesson", "SubjectID");

                    b.HasOne("DiplomaWork.Data.Models.Teacher", "Teacher")
                        .WithOne("Lesson")
                        .HasForeignKey("DiplomaWork.Data.Models.Lesson", "TeacherID");

                    b.Navigation("Classroom");

                    b.Navigation("Group");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Classroom", b =>
                {
                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Group", b =>
                {
                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Subject", b =>
                {
                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DiplomaWork.Data.Models.Teacher", b =>
                {
                    b.Navigation("Group");

                    b.Navigation("Lesson");
                });
#pragma warning restore 612, 618
        }
    }
}
